repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-ast
    - id: check-json
      exclude: asv.conf.json
    - id: check-toml
    - id: check-yaml
    - id: check-case-conflict
    - id: debug-statements
    - id: mixed-line-ending
      args: ['--fix=no']
  - repo: https://github.com/akaihola/darker
    rev: 1.7.2
    hooks:
      - id: darker
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: 'v0.0.288'
    hooks:
      - id: ruff
        types_or: [python, pyi, jupyter, toml]
