branches:
  only:
  - master
  # All release branches which start with "release/v", e.g. "release/v0.8.*"
  - /^release\/v\S+/
  # all release tags
  # The regexp is taken from PEP 440 (https://www.python.org/dev/peps/pep-0440/#appendix-b-parsing-version-strings-with-regular-expressions)
  - /^v([1-9][0-9]*!)?(0|[1-9][0-9]*)(\.(0|[1-9][0-9]*))*((a|b|rc)(0|[1-9][0-9]*))?(\.post(0|[1-9][0-9]*))?(\.dev(0|[1-9][0-9]*))?$/

language: python
sudo: required
dist: bionic
services:
  - xvfb
notifications:
  email: false

cache: pip

addons:
  apt_packages:
    - pandoc
    - libxkbcommon-x11-0 # needed for pyqt > 5.11 to work correctly with xvfb

python:
  - "3.7"
  - "3.8"
  # whitelist

# command to install dependencies and qcodes
# We want to fail early if there is an installation problem, so
# we install here, although we uninstall below
install:
    - pip install --upgrade pip setuptools wheel
    - pip install -r requirements.txt --use-feature=2020-resolver
    - pip install -r test_requirements.txt --use-feature=2020-resolver
    - pip install -r docs_requirements.txt --use-feature=2020-resolver
    - pip install .

script:
    - |
    # check that line endings are correct avoiding mixed windows/unix style line endings
    - pylint --reports=n --disable=all --enable=mixed-line-endings,unexpected-line-ending-format --expected-line-ending-format=LF qcodes
    # run benchmarks to make sure they are correct
    - |
      cd benchmarking
      asv machine --machine travis
      asv dev --machine travis
    - cd ..
    # rerun the tests from within a python session to ensure that all fixtures
    # are bundled correctly. To save time we only do this from python 3.7
    - |
      cd $HOME
      if [[ $TRAVIS_PYTHON_VERSION  == "3.7" ]]; then
        python -c "import sys; import qcodes; ec = qcodes.test(); sys.exit(ec)"
      fi
