name: "QCoDeS CI"

trigger:
  branches:
    include:
      - master

jobs:
  - job: "run_the_tests"
    pool:
      vmImage: "vs2017-win2016"

    steps:
      - task: UsePythonVersion@0
        inputs:
          versionSpec: '3.6'
          architecture: 'x64'
      - script: |
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r test_requirements.txt
          pip install -r docs_requirements.txt
          pip install -e .
        displayName: "Installation"
      - script: |
          mypy qcodes
        displayName: "mypy"
      - script: |
          cd qcodes\tests
          pytest
        displayName: "Pytest"
      - script: |
          cd docs
          make.bat htmlapi
        displayName: "docsbuild"
