name: qcodes
channels: 
 - defaults
 - conda-forge
dependencies:
 - h5py
 - matplotlib=2.2.3
 - pyqtgraph 
 - python=3.6
 - jsonschema
 - QtPy
 - sip
 - pyqt=5.9.2
 - numpy=1.15
 - jupyter=1.0.0
 - hypothesis
 - pytest
 - pytest-runner
 - spyder
 - pyzmq
 - pyyaml
 - lxml
 - scipy
 - ruamel_yaml
 - pyvisa=1.8
 - pip:
    - websockets>=3.2
