name: Cancel old jobs
on:
  workflow_run:
    workflows: ["build docs", "Run mypy and pytest"]
    types:
      - requested
jobs:
  cancel:
    runs-on: ubuntu-latest
    steps:
    - uses: styfle/cancel-workflow-action@0.9.1
      with:
        workflow_id: ${{ github.event.workflow.id }}
