name: Lint with Darker

on: [push, pull_request]

jobs:
  lint-with-darker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: akaihola/darker@1.4.1
        with:
          options: "--check --diff"
          src: "./qcodes"
          revision: "origin/master..."
          version: "1.4.1"
