name: Lint with Darker

on:
  push:
    branches:
      - 'main'
      - 'release/*'
  pull_request:

permissions:
  contents: read

jobs:
  lint-with-darker:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@63c24ba6bd7ba022e95695ff85de572c04a18142 # v2.7.0
        with:
          egress-policy: audit

      - uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v4.1.2
        with:
          fetch-depth: 0
      - uses: actions/setup-python@0a5c61591373683505ea898e09a3ea4f39ef2b9c # v5.0.0
        with:
          python-version: "3.11"
      - uses: akaihola/darker@d90b545f2d8b7b2721aba97aa49cea641f7b1a33 # 1.7.3
        with:
          options: "--check --diff"
          src: "./src/qcodes"
          revision: "origin/main..."
