name: Lint with Darker

on:
  push:
    branches:
      - 'main'
      - 'release/*'
  pull_request:

permissions:
  contents: read

jobs:
  lint-with-darker:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@v2
        with:
          egress-policy: audit

      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          fetch-depth: 0
      - uses: actions/setup-python@0a5c61591373683505ea898e09a3ea4f39ef2b9c # v5.0.0
        with:
          python-version: "3.11"
      - uses: akaihola/darker@ddcd430663c3a980ceb408ee05b7c90ba875d71b # 1.7.2
        with:
          options: "--check --diff"
          src: "./src/qcodes"
          revision: "origin/main..."
