name: Lint with Darker

on:
  push:
    branches:
      - 'main'
      - 'release/*'
  pull_request:

permissions:
  contents: read

jobs:
  lint-with-darker:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@v2
        with:
          egress-policy: audit

      - uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - uses: akaihola/darker@1.7.2
        with:
          options: "--check --diff"
          src: "./src/qcodes"
          revision: "origin/main..."
