name: build docs

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8]
    env:
      DISPLAY: ':99.0'

    steps:
    - uses: actions/checkout@v2
    - name: setup ubuntu-latest xvfb
      uses: ./.github/actions/setup-ubuntu-latest-xvfb
    - name: install pandoc ubuntu
      run: sudo apt install pandoc
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: prepare pip cache
      id: prepare-cache-pip
      uses: ./.github/actions/prepare-cache-pip
    - name: pip cache
      uses: actions/cache@v2
      with:
        path: ${{ steps.prepare-cache-pip.outputs.cache-dir }}
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}-${{ hashFiles('**/docs_reqirements.txt') }}-${{ hashFiles('**/setup.py') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: install requirements.txt
      run: |
        pip install -r requirements.txt --use-feature=2020-resolver
    - name: install docs_requirements.txt
      run: |
        pip install -r docs_requirements.txt --use-feature=2020-resolver
    - name: install qcodes
      run: pip install . --use-feature=2020-resolver
    - name: Build docs
      run: |
        cd docs
        make html
    - name: Upload build docs
      uses: actions/upload-artifact@v2
      with:
        name: docs_${{ matrix.python-version }}
        path: ./_build/html
