name: pre-commit hooks

on:
  pull_request:
  push:
    branches:
      - 'main'
      - 'release/*'

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@v2
      with:
        egress-policy: audit

    - uses: actions/checkout@v4.1.1
    - uses: actions/setup-python@v5
    - uses: pre-commit/action@v3.0.0
