name: Run mypy and pytest

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8]
    env:
      DISPLAY: ':99.0'

    steps:
    - name: setup ubuntu-latest xvfb
      run: |
        sudo apt install libxkbcommon-x11-0 libxcb-icccm4 libxcb-image0 libxcb-keysyms1 libxcb-randr0 libxcb-render-util0 libxcb-xinerama0 libxcb-xfixes0
        /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -screen 0 1920x1200x24 -ac +extension GLX
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: install requirements.txt
      run: |
        pip install -r requirements.txt
        pip install -r test_requirements.txt
    - name: install qcodes
      run: pip install .
    - name: Run Mypy
      run: mypy qcodes
    - name: Test with pytest
      run: |
        cd qcodes
        py.test -m "not serial" --cov=qcodes --cov-report xml --cov-config=.coveragerc --hypothesis-profile ci
        py.test -n 0 --dist no -m serial --cov-append --cov=qcodes --cov-report xml --cov-config=.coveragerc --hypothesis-profile ci
