name: Upload Python Package

on:
  push:
    tags:
      - v*

permissions:
  contents: read

jobs:
  deploy:

    runs-on: ubuntu-latest
    environment: pypi-release-env
    permissions:
      id-token: write
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@63c24ba6bd7ba022e95695ff85de572c04a18142 # v2.7.0
      with:
        egress-policy: audit

    - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
    - name: Set up Python
      uses: actions/setup-python@0a5c61591373683505ea898e09a3ea4f39ef2b9c # v5.0.0
      with:
        python-version: '3.10'
    - name: Install build deps
      run: pip install --upgrade pip setuptools wheel build
    - name: Build
      run: |
        python -m build
    - name: Install Twine
      run: pip install twine
    - name: Publish to pypi
      uses: pypa/gh-action-pypi-publish@2f6f737ca5f74c637829c0f5c3acd0e29ea5e8bf # release/v1
